# -*- coding: utf-8 -*-
"""Generate Dummy Aset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8qhOKnor1QbrsYtAkpgSGipV4A_-Gz_
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta

# 1. Pengaturan Awal
np.random.seed(42)
jumlah_aset = 450
tanggal_berdiri = datetime(2010, 1, 1)
tanggal_sekarang = datetime(2025, 12, 24)

# 2. Definisi Departemen
departemen_dict = {
    "Direksi": "DIR",
    "Engineering": "ENG",
    "Human Empowerment & Development": "HED",
    "Marketing & Business Development": "MBD",
    "Business Analyst": "BA",
    "Service Excellence": "SE",
    "FAT": "FAT",
    "QPC": "QPC"
}

daftar_pic = [
    "Aditya", "Budi", "Citra", "Dewi", "Eko",
    "Fajar", "Gita", "Hadi", "Indah", "Joko",
    "Kevin", "Laras", "Mahendra", "Nadia", "Oki",
    "Putri", "Rama", "Siti", "Tio", "Yusuf"
]

# Pemisahan Kategori IT & Non-IT dengan variasi harga yang mencakup batas VA/NVA (1 Juta)
katalog_aset = {
    "IT": [
        {"nama": "Laptop Lenovo ThinkPad", "harga_min": 12000000, "harga_max": 22000000},
        {"nama": "Infinix Xpad Tablet", "harga_min": 2500000, "harga_max": 3500000},
        {"nama": "Monitor Dell 24 Inch", "harga_min": 1800000, "harga_max": 3000000},
        {"nama": "Printer Epson L-Series", "harga_min": 2500000, "harga_max": 4500000},
        {"nama": "Server Dell PowerEdge", "harga_min": 45000000, "harga_max": 85000000},
        {"nama": "Projector BenQ", "harga_min": 5000000, "harga_max": 9000000},
        # Contoh IT yang di bawah 1 juta (NVA)
        {"nama": "Mouse Wireless Logitech", "harga_min": 150000, "harga_max": 350000},
        {"nama": "Keyboard Eksternal", "harga_min": 200000, "harga_max": 450000},
        {"nama": "USB Hub Type-C", "harga_min": 250000, "harga_max": 600000}
    ],
    "Non-IT": [
        {"nama": "Meja Kerja Ergonomis", "harga_min": 1200000, "harga_max": 2500000},
        {"nama": "Kursi Kantor Hidrolik", "harga_min": 1100000, "harga_max": 1800000},
        {"nama": "AC Split Daikin", "harga_min": 4000000, "harga_max": 7000000},
        {"nama": "Lemari Arsip Besi", "harga_min": 1500000, "harga_max": 3000000},
        {"nama": "Sofa Ruang Tamu", "harga_min": 5000000, "harga_max": 12000000},
        {"nama": "Papan Tulis Kaca (Glassboard)", "harga_min": 1200000, "harga_max": 2000000},
        # Contoh Non-IT yang di bawah 1 juta (NVA)
        {"nama": "Kursi Plastik Napolly", "harga_min": 150000, "harga_max": 250000},
        {"nama": "Tempat Sampah Injak", "harga_min": 75000, "harga_max": 150000},
        {"nama": "Kipas Angin Dinding", "harga_min": 350000, "harga_max": 650000}
    ]
}

ruangan_dict = {
    "Direksi": ["Ruang Direktur Utama", "Ruang Meeting Eksekutif"],
    "Engineering": ["Ruang Dev", "Lab Kalibrasi", "Workshop"],
    "Human Empowerment & Development": ["Ruang HED", "Ruang Interview", "Training Center"],
    "Marketing & Business Development": ["Ruang Kreatif", "Studio Foto/Konten"],
    "Business Analyst": ["Ruang Analis Data", "War Room Project"],
    "Service Excellence": ["Area Customer Service", "Command Center"],
    "FAT": ["Ruang Finance", "Gudang Arsip Finansial"],
    "QPC": ["Ruang Quality Control", "Lab Audit & Kepatuhan"]
}

tracker_urutan = {}
data = []

# 3. Looping Pembuatan Data
for _ in range(jumlah_aset):
    dept = np.random.choice(list(departemen_dict.keys()))
    singkatan_dept = departemen_dict[dept]

    selisih_hari = (tanggal_sekarang - tanggal_berdiri).days
    hari_acak = np.random.randint(0, selisih_hari)
    tgl_pembelian = tanggal_berdiri + timedelta(days=hari_acak)
    tahun_dua_angka = tgl_pembelian.strftime("%y")

    key_tracker = (singkatan_dept, tahun_dua_angka)
    if key_tracker not in tracker_urutan:
        tracker_urutan[key_tracker] = 1
    else:
        tracker_urutan[key_tracker] += 1

    nomor_urut = tracker_urutan[key_tracker]
    kode_aset = f"ASSET-{singkatan_dept}-{tahun_dua_angka}-{nomor_urut:05d}"

    kategori = np.random.choice(["IT", "Non-IT"], p=[0.45, 0.55])
    item_pilihan = np.random.choice(katalog_aset[kategori])
    nama_aset = item_pilihan["nama"]
    harga_satuan = int(np.random.uniform(item_pilihan["harga_min"], item_pilihan["harga_max"]))

    # --- Penentuan VA vs NVA berdasarkan Harga Satuan ---
    sub_kategori = "VA" if harga_satuan >= 1000000 else "NVA"

    kuantitas = int(np.random.choice([1, 2, 5, 10], p=[0.75, 0.15, 0.07, 0.03]))
    total_harga = harga_satuan * kuantitas
    pic = np.random.choice(daftar_pic)

    kondisi = np.random.choice(["Baik", "Tidak Baik", "Diperbaiki"], p=[0.83, 0.07, 0.10])

    if kondisi == "Diperbaiki":
        status = "Aktif"
    elif kondisi == "Tidak Baik":
        status = np.random.choice(["Non Aktif Disposal", "Non Aktif Dijual", "Non Aktif Donasi"], p=[0.6, 0.2, 0.2])
    else:
        status = np.random.choice(["Aktif", "Non Aktif Dijual", "Non Aktif Donasi"], p=[0.96, 0.02, 0.02])

    kantor_cabang = np.random.choice(["Kantor Pusat", "Cabang Bandung", "Cabang Surabaya"], p=[0.65, 0.20, 0.15])
    ruangan = np.random.choice(ruangan_dict[dept])
    lokasi_fisik = f"{kantor_cabang} - {ruangan}"

    data.append({
        "Kode Aset": kode_aset,
        "Nama Aset": nama_aset,
        "Kategori": kategori,
        "Sub-Kategori": sub_kategori,
        "Departemen": dept,
        "Tanggal Pembelian": tgl_pembelian.strftime("%Y-%m-%d"),
        "Kuantitas": kuantitas,
        "Harga Satuan": harga_satuan,
        "Total Harga": total_harga,
        "PIC / User": pic,
        "Kondisi Barang": kondisi,
        "Status": status,
        "Lokasi Fisik": lokasi_fisik
    })

# 4. Konversi ke DataFrame & Urutkan berdasarkan Tanggal
df_dashboard = pd.DataFrame(data)
df_dashboard = df_dashboard.sort_values(by="Tanggal Pembelian").reset_index(drop=True)

# 5. Eksport ke Excel (*.xlsx)
nama_file = "dashboard_aset_perusahaan.xlsx"
df_dashboard.to_excel(nama_file, index=False, sheet_name="Data Inventaris Aset")

print(f"Sukses membuat {len(df_dashboard)} baris data inventaris aset!")
print(f"File berhasil disimpan dalam format Excel dengan nama: '{nama_file}'")